#!/usr/bin/env bash
set -euo pipefail

DIST_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"

normalize_arch() {
  case "${1:-$(uname -m)}" in
    x86_64|amd64)
      printf 'amd64\n'
      ;;
    aarch64|arm64)
      printf 'arm64\n'
      ;;
    *)
      printf '%s\n' "${1:-$(uname -m)}"
      ;;
  esac
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    printf 'missing required command: %s\n' "$1" >&2
    exit 1
  }
}

BUNDLE_NAME="${BUNDLE_NAME:-sarus-suite}"
BUNDLE_VERSION="${BUNDLE_VERSION:-dev}"
TARGET_ARCH="${TARGET_ARCH:-$(normalize_arch)}"

WORK_DIR="${WORK_DIR:-${DIST_ROOT}/.work}"
CACHE_DIR="${CACHE_DIR:-${DIST_ROOT}/.cache}"
SRC_DIR="${SRC_DIR:-${WORK_DIR}/src}"
BUILD_DIR="${BUILD_DIR:-${WORK_DIR}/build/${TARGET_ARCH}}"
DIST_DIR="${DIST_DIR:-${DIST_ROOT}/dist}"
OUT_DIR="${OUT_DIR:-${DIST_DIR}/${BUNDLE_NAME}-${BUNDLE_VERSION}-${TARGET_ARCH}}"
BUNDLE_ROOT="${BUNDLE_ROOT:-${OUT_DIR}/${BUNDLE_NAME}}"

PARALLAX_REPO="${PARALLAX_REPO:-https://github.com/sarus-suite/parallax.git}"
PARALLAX_REF="${PARALLAX_REF:-parallax-static}"
PARALLAX_SRC_DIR="${PARALLAX_SRC_DIR:-${SRC_DIR}/parallax}"
PARALLAX_DEVCONTAINER_CONFIG="${PARALLAX_DEVCONTAINER_CONFIG:-.devcontainer/alpine/devcontainer.json}"
PARALLAX_BUILD_SCRIPT="${PARALLAX_BUILD_SCRIPT:-.devcontainer/scripts/build-static.sh}"
PARALLAX_OUT_REL="${PARALLAX_OUT_REL:-dist/parallax-static}"
PARALLAX_BIN="${PARALLAX_BIN:-${PARALLAX_SRC_DIR}/${PARALLAX_OUT_REL}}"
PARALLAX_MOUNT_PROGRAM_REL="${PARALLAX_MOUNT_PROGRAM_REL:-scripts/parallax-mount-program.sh}"

SARUSCTL_REPO="${SARUSCTL_REPO:-https://github.com/sarus-suite/cluster-tooling.git}"
SARUSCTL_REF="${SARUSCTL_REF:-sarusctl-home-config}"
SARUSCTL_SRC_DIR="${SARUSCTL_SRC_DIR:-${SRC_DIR}/cluster-tooling}"
SARUSCTL_DEVCONTAINER_CONFIG="${SARUSCTL_DEVCONTAINER_CONFIG:-.devcontainer/alpine/devcontainer.json}"
SARUSCTL_BUILD_MODE="${SARUSCTL_BUILD_MODE:-devcontainer}"
SARUSCTL_PREBUILT_BIN="${SARUSCTL_PREBUILT_BIN:-}"
SARUSCTL_OUT_REL="${SARUSCTL_OUT_REL:-dist/sarusctl}"
SARUSCTL_BIN="${SARUSCTL_BIN:-${BUILD_DIR}/sarusctl}"

PERFEXT_REPO="${PERFEXT_REPO:-https://github.com/sarus-suite/performance-extensions.git}"
PERFEXT_REF="${PERFEXT_REF:-main}"
PERFEXT_SRC_DIR="${PERFEXT_SRC_DIR:-${SRC_DIR}/performance-extensions}"
PERFEXT_DEVCONTAINER_CONFIG="${PERFEXT_DEVCONTAINER_CONFIG:-.devcontainer/devcontainer.json}"
PERFEXT_BUILD_MODE="${PERFEXT_BUILD_MODE:-devcontainer}"
PERFEXT_BUILD_DIR="${PERFEXT_BUILD_DIR:-${BUILD_DIR}/performance-extensions}"
PERFEXT_LDCACHE_HOOK_BIN="${PERFEXT_LDCACHE_HOOK_BIN:-${PERFEXT_BUILD_DIR}/ldcache_hook}"
PERFEXT_MPS_HOOK_BIN="${PERFEXT_MPS_HOOK_BIN:-${PERFEXT_BUILD_DIR}/mps_hook}"
PERFEXT_PCE_HOOK_BIN="${PERFEXT_PCE_HOOK_BIN:-${PERFEXT_BUILD_DIR}/pce_hook}"
PERFEXT_PC_INJECTION_HOOK_BIN="${PERFEXT_PC_INJECTION_HOOK_BIN:-${PERFEXT_BUILD_DIR}/pc_injection_hook}"
PERFEXT_MKHOMEDIR_BIN="${PERFEXT_MKHOMEDIR_BIN:-${PERFEXT_BUILD_DIR}/mkhomedir}"
PERFEXT_SETHOMEVAR_BIN="${PERFEXT_SETHOMEVAR_BIN:-${PERFEXT_BUILD_DIR}/sethomevar}"

PODMAN_MODE="${PODMAN_MODE:-download-static}"
PODMAN_STATIC_VERSION="${PODMAN_STATIC_VERSION:-v5.8.1}"
PODMAN_STATIC_PREFIX="${PODMAN_STATIC_PREFIX:-${CACHE_DIR}/podman-static/${PODMAN_STATIC_VERSION}/${TARGET_ARCH}}"

MKSQUASHFS_VERSION="${MKSQUASHFS_VERSION:-4.7.5}"
RSYNC_VERSION="${RSYNC_VERSION:-3.4.1}"
INOTIFY_TOOLS_VERSION="${INOTIFY_TOOLS_VERSION:-4.23.9.0}"
SQUASHFUSE_VERSION="${SQUASHFUSE_VERSION:-0.6.1}"
FUSE_OVERLAYFS_VERSION="${FUSE_OVERLAYFS_VERSION:-v1.17}"
LIBFUSE_VERSION="${LIBFUSE_VERSION:-3.18.2}"

MKSQUASHFS_BIN="${MKSQUASHFS_BIN:-${BUILD_DIR}/mksquashfs}"
RSYNC_BIN="${RSYNC_BIN:-${BUILD_DIR}/rsync}"
INOTIFYWAIT_BIN="${INOTIFYWAIT_BIN:-${BUILD_DIR}/inotifywait}"
SQUASHFUSE_LL_BIN="${SQUASHFUSE_LL_BIN:-${BUILD_DIR}/squashfuse_ll}"
FUSE_OVERLAYFS_BIN="${FUSE_OVERLAYFS_BIN:-${BUILD_DIR}/fuse-overlayfs}"
FUSERMOUNT3_BIN="${FUSERMOUNT3_BIN:-${BUILD_DIR}/fusermount3}"

RUNTIME_BIN_DIR="${RUNTIME_BIN_DIR:-${BUNDLE_ROOT}/bin}"
RUNTIME_LIBEXEC_DIR="${RUNTIME_LIBEXEC_DIR:-${BUNDLE_ROOT}/libexec}"
RUNTIME_HOOK_BIN_DIR="${RUNTIME_HOOK_BIN_DIR:-${RUNTIME_LIBEXEC_DIR}/oci/hooks}"
RUNTIME_CONTAINERS_ETC_DIR="${RUNTIME_CONTAINERS_ETC_DIR:-${BUNDLE_ROOT}/etc/containers}"
RUNTIME_CONTAINERS_MODULES_DIR="${RUNTIME_CONTAINERS_MODULES_DIR:-${RUNTIME_CONTAINERS_ETC_DIR}/containers.conf.modules}"
RUNTIME_CONTAINERS_HOOKS_DIR="${RUNTIME_CONTAINERS_HOOKS_DIR:-${RUNTIME_CONTAINERS_ETC_DIR}/oci/hooks.d}"
RUNTIME_PARALLAX_ETC_DIR="${RUNTIME_PARALLAX_ETC_DIR:-${BUNDLE_ROOT}/etc/parallax}"
RUNTIME_SARUS_SUITE_ETC_DIR="${RUNTIME_SARUS_SUITE_ETC_DIR:-${BUNDLE_ROOT}/etc/sarus-suite}"
RUNTIME_SHARE_DIR="${RUNTIME_SHARE_DIR:-${BUNDLE_ROOT}/share}"
RUNTIME_LICENSE_DIR="${RUNTIME_LICENSE_DIR:-${RUNTIME_SHARE_DIR}/licenses}"
RUNTIME_MANIFEST="${RUNTIME_MANIFEST:-${RUNTIME_SHARE_DIR}/manifest.txt}"

SARUS_SUITE_BIN_PLACEHOLDER='@@SARUS_SUITE_BIN@@'
SARUS_SUITE_HOOK_BIN_PLACEHOLDER='@@SARUS_SUITE_HOOK_BIN@@'
SARUS_SUITE_STATE_PLACEHOLDER='@@SARUS_SUITE_STATE@@'
SARUS_SUITE_RUNTIME_PLACEHOLDER='@@SARUS_SUITE_RUNTIME@@'
SARUS_SUITE_CONFIG_PLACEHOLDER='@@SARUS_SUITE_CONFIG@@'
SARUS_SUITE_PODMAN_ROOT_PLACEHOLDER='@@SARUS_SUITE_PODMAN_ROOT@@'
SARUS_SUITE_PODMAN_RUNROOT_PLACEHOLDER='@@SARUS_SUITE_PODMAN_RUNROOT@@'
SARUS_SUITE_PARALLAX_STORE_PLACEHOLDER='@@SARUS_SUITE_PARALLAX_STORE@@'
