parallax_imagestore = "@@SARUS_SUITE_PARALLAX_STORE@@"
parallax_mount_program = "@@SARUS_SUITE_BIN@@/parallax-mount-program"
parallax_path = "@@SARUS_SUITE_BIN@@/parallax"
parallax_mp_logfile = "@@SARUS_SUITE_STATE@@/logs/parallax-mount.log"
parallax_mp_squashfuse_path = "@@SARUS_SUITE_BIN@@/squashfuse_ll"
podman_module = "hpc"
podman_path = "@@SARUS_SUITE_BIN@@/podman"
podman_tmp_path = "@@SARUS_SUITE_RUNTIME@@/tmp"
runtime_path = "@@SARUS_SUITE_BIN@@/crun"
