parallax_imagestore = "@@SARUS_SUITE_PARALLAX_STORE@@"
parallax_mount_program = "@@SARUS_SUITE_BIN@@/parallax-mount-program"
parallax_path = "@@SARUS_SUITE_BIN@@/parallax"
@@SARUS_SUITE_PARALLAX_MP_LOGFILE_LINE@@
parallax_mp_squashfuse_path = "@@SARUS_SUITE_BIN@@/squashfuse_ll"
podman_module = "hpc"
podman_path = "@@SARUS_SUITE_BIN@@/podman"
@@SARUS_SUITE_PODMAN_TMP_PATH_LINE@@
runtime_path = "@@SARUS_SUITE_BIN@@/crun"
